/** Storable-style custom templates that ship with the facility setup.
 *  Admin-created/customized rows are never overwritten by the templates API.
 */
export const DEFAULT_CUSTOM_TEMPLATES = [
  {
    name: 'Action Required - Please Read',
    type: 'custom' as const,
    emailSubject: 'Action Required - Please Read',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>Please review this important notice from [[FACILITY_NAME]].</p>',
    textContent: '[[FACILITY_NAME]]: Please review this important notice.',
    postcardContent: '',
    emailEnabled: false,
    textEnabled: false,
    printEnabled: false,
    rule: 'manual' as const,
    daysPastDue: null,
    description: '',
  },
  {
    name: 'Action Required - Please Read - 10 Days Notice',
    type: 'custom' as const,
    emailSubject: 'Action Required - Please Read - 10 Days Notice',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>Please review this important 10 day notice from [[FACILITY_NAME]].</p>',
    textContent: '[[FACILITY_NAME]]: Please review this important 10 day notice.',
    postcardContent: '',
    emailEnabled: false,
    textEnabled: false,
    printEnabled: false,
    rule: 'manual' as const,
    daysPastDue: null,
    description: '',
  },
  {
    name: 'Facility Gate',
    type: 'custom' as const,
    emailSubject: 'Facility Gate',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>This is an update about your facility gate access.</p>',
    textContent: '[[FACILITY_NAME]]: This is an update about your gate access.',
    postcardContent: '',
    emailEnabled: false,
    textEnabled: false,
    printEnabled: false,
    rule: 'manual' as const,
    daysPastDue: null,
    description: '',
  },
  {
    name: 'Mass email example',
    type: 'custom' as const,
    emailSubject: 'Mass email example',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>This is a message from [[FACILITY_NAME]].</p>',
    textContent: '[[FACILITY_NAME]]: This is a message from the facility.',
    postcardContent: '',
    emailEnabled: false,
    textEnabled: false,
    printEnabled: false,
    rule: 'manual' as const,
    daysPastDue: null,
    description: '',
  },
  {
    name: 'Notice of "Lockout" of Storage Unit / Notice of Intended Sale of Personal Property At Auction',
    type: 'custom' as const,
    emailSubject: 'Notice of Lockout / Intended Sale - [[FACILITY_NAME]]',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>Your storage account at [[FACILITY_NAME]] is past due. Please contact us immediately regarding unit [[UNIT_NUMBER]].</p>',
    textContent: '[[FACILITY_NAME]]: Your storage account is past due. Please contact us immediately.',
    postcardContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>Your storage account at [[FACILITY_NAME]] is past due. Please contact us immediately.</p>',
    emailEnabled: true,
    textEnabled: true,
    printEnabled: false,
    rule: 'pre_lien' as const,
    daysPastDue: 15,
    description: '',
  },
  {
    name: 'Notice of Foreclosure of Lien and Sale of Personal Property',
    type: 'custom' as const,
    emailSubject: 'Notice of Foreclosure of Lien and Sale of Personal Property',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>Your storage unit at [[FACILITY_NAME]] is scheduled for auction. Please pay [[BALANCE]] or contact us immediately.</p>',
    textContent: '[[FACILITY_NAME]]: Your storage unit is scheduled for auction. Balance: [[BALANCE]]. Contact us immediately.',
    postcardContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>Your storage unit at [[FACILITY_NAME]] is scheduled for auction. Balance: [[BALANCE]].</p>',
    emailEnabled: true,
    textEnabled: true,
    printEnabled: true,
    rule: 'auction' as const,
    daysPastDue: 37,
    description: '',
  },
  {
    name: 'Past Due Notice',
    type: 'custom' as const,
    emailSubject: 'Past Due Notice - [[FACILITY_NAME]]',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>Your account balance of [[BALANCE]] is past due. Please make a payment as soon as possible.</p>',
    textContent: '[[FACILITY_NAME]]: Your account balance of [[BALANCE]] is past due. Please make a payment.',
    postcardContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>Your account balance of [[BALANCE]] is past due.</p>',
    emailEnabled: true,
    textEnabled: true,
    printEnabled: false,
    rule: 'late' as const,
    daysPastDue: 5,
    description: '',
  },
  {
    name: 'Past Due Warning',
    type: 'custom' as const,
    emailSubject: 'Past Due Warning - [[FACILITY_NAME]]',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>Your storage account has an outstanding balance of [[BALANCE]]. Please make a payment to avoid further action.</p>',
    textContent: '[[FACILITY_NAME]]: Your account has an outstanding balance of [[BALANCE]]. Please make a payment.',
    postcardContent: '',
    emailEnabled: true,
    textEnabled: true,
    printEnabled: false,
    rule: 'late' as const,
    daysPastDue: 4,
    description: '',
  },
  {
    name: 'Tenant Protection',
    type: 'custom' as const,
    emailSubject: 'Tenant Protection',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>This is information about tenant protection at [[FACILITY_NAME]].</p>',
    textContent: '[[FACILITY_NAME]]: Tenant protection information is available for your account.',
    postcardContent: '',
    emailEnabled: false,
    textEnabled: false,
    printEnabled: false,
    rule: 'manual' as const,
    daysPastDue: null,
    description: '',
  },
  {
    name: 'Termination of Lease Agreement',
    type: 'custom' as const,
    emailSubject: 'Termination of Lease Agreement',
    emailContent: '<p>Dear [[CUSTOMER_NAME]],</p><p>This notice concerns the termination of your lease agreement with [[FACILITY_NAME]].</p>',
    textContent: '[[FACILITY_NAME]]: This notice concerns the termination of your lease agreement.',
    postcardContent: '',
    emailEnabled: false,
    textEnabled: false,
    printEnabled: false,
    rule: 'manual' as const,
    daysPastDue: null,
    description: '',
  },
]
