export const DEFAULT_SETTINGS = {
  // Facility
  facilityName: 'Tuscany Village Self Storage',
  facilityAddress: '2519 Highway 116',
  facilityCity: 'Caryville',
  facilityState: 'TN',
  facilityZip: '37714',
  facilityPhone: '(865) 426-2100',
  facilityEmail: 'Tuscanystorage@gmail.com',
  accessHoursStart: '05:00',
  accessHoursEnd: '22:00',
  // Locale
  locale: 'en-US',
  currency: 'USD',
  dateFormat: 'MM/DD/YYYY',
  timeZone: 'America/New_York',
  phoneFormat: '(555) 555-5555',
  dimensionFormat: '10w x 10l x 10h',
  // Tax
  taxRate: 9.75,
  // Billing
  billingDaysBeforeDue: 7,
  daysRequiredBeforeBillingDay: 0,
  // Fees
  lateFeeAfterDays: 5,
  lateFeeAmount: 2000,
  nsfFeeAmount: 3500,
  auctionFeeAmount: 5000,
  // Rental options
  enablePrepay: false,
  disablePartialPaymentsForLockedOut: false,
  saveUnpaidRentals: false,
  autoAcknowledgeRentals: false,
  enableAdditionalDeposits: false,
  customerRentalProrating: false,
  defaultProratingForManagerRentals: false,
  // Reservations
  enableReservations: false,
  reservationLimitDays: 0,
  // Customer permissions
  customersCanEditProfile: true,
  customersCanEditBilling: true,
  customersCanScheduleMoveOuts: true,
  // New renter instructions
  newRenterInstructions:
    'Gate LOCKS at 10:00 p.m. and will not open in or out. If you find yourself locked in the facility after 10PM, call (865) 426-2100 to be let out remotely.',
  // Lockout
  lockoutRequireApprovalAuto: false,
  lockoutRequireApprovalManual: false,
  // Custom fees
  customFees: [] as Array<{ id: string; name: string; amount: number; description: string; active: boolean }>,
  // Late / Lien escalation
  lateLienEvents: [
    { id: 'evt_late_1',    status: 'late'       as const, daysPastDue: 1,  notifyEmail: false, notifyText: false, notifyLetter: false, notificationTemplate: '',                                                                                          fees: [],                                                              actions: [] },
    { id: 'evt_late_4',    status: 'late'       as const, daysPastDue: 4,  notifyEmail: true,  notifyText: true,  notifyLetter: false, notificationTemplate: 'Past Due Warning',                                                                            fees: [],                                                              actions: [] },
    { id: 'evt_late_5',    status: 'late'       as const, daysPastDue: 5,  notifyEmail: true,  notifyText: true,  notifyLetter: false, notificationTemplate: 'Past Due Notice',                                                                              fees: [{ name: 'Past Due Fee', amount: 2000 }],                        actions: [] },
    { id: 'evt_lockout_9', status: 'locked_out' as const, daysPastDue: 9,  notifyEmail: true,  notifyText: true,  notifyLetter: false, notificationTemplate: 'Past Due Notice',                                                                              fees: [],                                                              actions: ['lockout'] },
    { id: 'evt_prelien_15',status: 'pre_lien'   as const, daysPastDue: 15, notifyEmail: true,  notifyText: true,  notifyLetter: false, notificationTemplate: 'Notice of Lockout of Storage Unit / Notice of Intended Sale of Personal Property At Auction',  fees: [],                                                              actions: [] },
    { id: 'evt_lien_30',   status: 'lien'       as const, daysPastDue: 30, notifyEmail: true,  notifyText: true,  notifyLetter: false, notificationTemplate: 'Notice of Lockout of Storage Unit / Notice of Intended Sale of Personal Property At Auction',  fees: [],                                                              actions: [] },
    { id: 'evt_auction_37',status: 'auction'    as const, daysPastDue: 37, notifyEmail: true,  notifyText: true,  notifyLetter: true,  notificationTemplate: 'Notice of Foreclosure of Lien and Sale of Personal Property',                                  fees: [{ name: 'Advertisement Fee', amount: 2500 }, { name: 'Cut Lock Fee', amount: 2000 }], actions: ['queue_print'] },
  ],
  // Gate
  gateAutoAssign: true,
  gateAutoAssignMethod: 'phone_last4' as const,
  gateCodeLength: 4,
  gateAutoLockout: true,
  gateTextToOpen: false,
  gateTextToOpenNumber: '',
  gateControllerType: '',
  gateNodeId: '',
  gateApiEndpoint: '',
  gateApiKey: '',
  // Agreement
  agreementTitle: 'Storage Lease Agreement',
  agreementTemplate: {
    type: 'doc',
    content: [
      { type: 'heading', attrs: { level: 1, textAlign: 'center' }, content: [{ type: 'text', text: 'Storage Rental Agreement' }] },
      { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: 'Tuscany Village Self Storage · [[FACILITY_NAME]]' }] },
      { type: 'horizontalRule' },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '1. Parties' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'This Storage Rental Agreement ("Agreement") is entered into as of [[DATE]] between Tuscany Village Self Storage ("Operator") and the following tenant:' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Name: ', marks: [{ type: 'bold' }] }, { type: 'text', text: '[[CUSTOMER_NAME]]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Address: ', marks: [{ type: 'bold' }] }, { type: 'text', text: '[[CUSTOMER_ADDRESS]]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Phone: ', marks: [{ type: 'bold' }] }, { type: 'text', text: '[[CUSTOMER_PHONE_NUMBER]]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Email: ', marks: [{ type: 'bold' }] }, { type: 'text', text: '[[EMAIL_ADDRESS]]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '2. Storage Unit' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Unit Number: ', marks: [{ type: 'bold' }] }, { type: 'text', text: '[[UNIT]]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Unit Size: ', marks: [{ type: 'bold' }] }, { type: 'text', text: '[[UNIT_SIZE]]' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Gate Access Code: ', marks: [{ type: 'bold' }] }, { type: 'text', text: '[[CUSTOMER_ACCESS_CODE]]' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '3. Rent & Deposit' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Monthly Rent: ', marks: [{ type: 'bold' }] }, { type: 'text', text: '[[RENT]] due on the same day each month.' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Security Deposit: ', marks: [{ type: 'bold' }] }, { type: 'text', text: '[[DEPOSIT]] (refundable upon satisfactory move-out).' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '4. Term' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'This Agreement begins on [[DATE]] and continues on a month-to-month basis until terminated by either party with at least 10 days written notice.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '5. Use of Unit' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Tenant agrees to use the storage unit solely for the storage of personal or business property and not for any illegal purpose. Tenant shall not store flammable, explosive, hazardous materials, living beings, food, or perishable items.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '6. Access' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'The facility is accessible during posted access hours. After-hours access is not permitted. The gate access code is personal and must not be shared.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '7. Late Fees' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Rent not received within 5 days of the due date is subject to a late fee. Continued non-payment may result in lien sale proceedings in accordance with applicable state law.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '8. Limitation of Liability' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Operator is not responsible for loss, theft, or damage to stored property. Tenant is encouraged to maintain renter\'s insurance for the full value of stored items.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '9. Termination' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'Either party may terminate this Agreement with 10 days written notice. Upon termination, Tenant must remove all property and return the unit in clean condition.' }] },
      { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '10. Agreement' }] },
      { type: 'paragraph', content: [{ type: 'text', text: 'By signing below, Tenant acknowledges having read, understood, and agreed to all terms of this Storage Rental Agreement.' }] },
      { type: 'horizontalRule' },
      { type: 'paragraph', content: [{ type: 'text', text: 'Date: [[DATE]]' }] },
    ],
  },
  // Customer form fields
  customerFormFields: [
    { key: 'name',              label: 'Name',                                             showOnSignup: true,  requiredOnSignup: true,  showOnWaitingList: true,  requiredOnWaitingList: true,  isCustom: false, order: 0 },
    { key: 'address',           label: 'Address',                                          showOnSignup: true,  requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 1 },
    { key: 'city',              label: 'City',                                             showOnSignup: true,  requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 2 },
    { key: 'state',             label: 'State/Province',                                   showOnSignup: true,  requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 3 },
    { key: 'zip',               label: 'Zip/Postal Code',                                  showOnSignup: true,  requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 4 },
    { key: 'phone',             label: 'Phone',                                            showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 5 },
    { key: 'cellPhone',         label: 'Cell Phone',                                       showOnSignup: true,  requiredOnSignup: false, showOnWaitingList: true,  requiredOnWaitingList: true,  isCustom: false, order: 6 },
    { key: 'driversLicense',    label: 'Drivers license number',                           showOnSignup: true,  requiredOnSignup: true,  showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 7 },
    { key: 'driversLicenseState', label: 'Drivers license state',                          showOnSignup: true,  requiredOnSignup: true,  showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 8 },
    { key: 'ssn',               label: 'Social security number',                           showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 9 },
    { key: 'employerName',      label: 'Employer name',                                    showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 10 },
    { key: 'employerPhone',     label: 'Employer phone',                                   showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 11 },
    { key: 'emergencyContact',  label: 'Emergency contact',                                showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 12 },
    { key: 'emergencyPhone',    label: 'Emergency phone',                                  showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 13 },
    { key: 'idPhoto',           label: 'Photo ID (Driver\'s License or Government Issued ID)', showOnSignup: true, requiredOnSignup: true, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 14 },
    { key: 'alternateContact',  label: 'Alternate Contact',                                showOnSignup: true,  requiredOnSignup: true,  showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 15 },
    { key: 'alternateAddress',  label: 'Alternate Address',                                showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 16 },
    { key: 'alternateCity',     label: 'Alternate City',                                   showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 17 },
    { key: 'alternateState',    label: 'Alternate State/Province',                         showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 18 },
    { key: 'alternateZip',      label: 'Alternate Zip/Postal Code',                        showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 19 },
    { key: 'alternatePhone',    label: 'Alternate Phone Number',                           showOnSignup: true,  requiredOnSignup: true,  showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 20 },
    { key: 'alternateEmail',    label: 'Alternate Email',                                  showOnSignup: true,  requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 21 },
    { key: 'referralSource',    label: 'Referred by',                                      showOnSignup: true,  requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 22 },
    { key: 'securityQuestion',  label: 'Security question',                                showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 23 },
    { key: 'securityAnswer',    label: 'Security answer',                                  showOnSignup: false, requiredOnSignup: false, showOnWaitingList: false, requiredOnWaitingList: false, isCustom: false, order: 24 },
  ],
}
